function randomInt(n){const a=new Uint32Array(1),limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(a);}while(a[0]>=limit);return a[0]%n;}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=randomInt(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function parseNumbers(text,label){if(!text.trim())return [];const tokens=text.trim().split(/[,;\s]+/);if(tokens.some(t=>!/^\d+$/.test(t)))throw Error(label+': use student numbers separated by commas or spaces.');const nums=tokens.map(Number);if(new Set(nums).size!==nums.length)throw Error(label+': a number appears more than once.');return nums;}
export const MAX_GROUP_SIZE=6,MAX_GROUPS=8,MAX_PRESENT=MAX_GROUP_SIZE*MAX_GROUPS;
export function groupCount(n){if(!Number.isInteger(n)||n<1||n>MAX_PRESENT)throw Error('At most 48 students can be present: 8 groups of up to 6.');return Math.ceil(n/MAX_GROUP_SIZE);}
export function solve(c){const roster=c.roster,k=groupCount(roster.length),parent=new Map(roster.map(v=>[v,v]));const root=v=>{while(parent.get(v)!==v)v=parent.get(v);return v;};for(const line of c.together)for(const v of line.slice(1))parent.set(root(v),root(line[0]));const map=new Map();for(const v of roster){const r=root(v);if(!map.has(r))map.set(r,[]);map.get(r).push(v);}const blocks=[...map.values()],bi=new Map();blocks.forEach((b,i)=>b.forEach(v=>bi.set(v,i)));for(const b of blocks)if(b.length>MAX_GROUP_SIZE)throw Error('The together requests link '+b.join(', ')+'. That is '+b.length+' students, exceeding the maximum of six.');for(const line of c.apart)if(line.length>k)throw Error('A keep-apart set has '+line.length+' students, but there are only '+k+' groups. Revise this request.');const edges=blocks.map(()=>new Set());for(const line of c.apart)for(let i=0;i<line.length;i++)for(let j=i+1;j<line.length;j++){const a=bi.get(line[i]),b=bi.get(line[j]);if(a===b)throw Error('Students '+line[i]+' and '+line[j]+' are linked by together requests but also requested apart. Edit one of these requests.');edges[a].add(b);edges[b].add(a);}const balancedCaps=Array.from({length:k},(_,i)=>Math.floor(roster.length/k)+(i<roster.length%k?1:0));if(!c.together.length&&!c.apart.length){const bag=shuffle([...roster]);let at=0;return {groups:shuffle(balancedCaps.map(size=>bag.slice(at,at+=size))).map(g=>g.sort((a,b)=>a-b)),balanced:true};}
let timedOut=false;const search=(caps)=>{const start=performance.now();let steps=0;const bins=Array.from({length:k},()=>[]),sizes=Array(k).fill(0),order=shuffle(blocks.map((_,i)=>i)).sort((a,b)=>blocks[b].length-blocks[a].length||edges[b].size-edges[a].size);function dfs(depth){if(++steps>400000||performance.now()-start>1500){timedOut=true;return false;}if(depth===order.length)return sizes.every(v=>v>0);if(sizes.filter(v=>v===0).length>order.length-depth)return false;const b=order[depth],seenEmpty=new Set();for(const g of shuffle(Array.from({length:k},(_,i)=>i))){if(sizes[g]+blocks[b].length>caps[g]||bins[g].some(v=>edges[b].has(v)))continue;if(!sizes[g]){if(seenEmpty.has(caps[g]))continue;seenEmpty.add(caps[g]);}bins[g].push(b);sizes[g]+=blocks[b].length;if(dfs(depth+1))return true;bins[g].pop();sizes[g]-=blocks[b].length;if(timedOut)return false;}return false;}return dfs(0)?bins.map(bin=>bin.flatMap(i=>blocks[i])):null;};
let groups=search(balancedCaps);if(!groups){timedOut=false;groups=search(Array(k).fill(MAX_GROUP_SIZE));}if(!groups)throw Error(timedOut?'The search reached its time limit. Try again, or simplify the requests. No rules were ignored.':'These requests cannot fit into '+k+' groups with at most six students. Revise the requests and check again.');groups=shuffle(groups).map(g=>g.sort((a,b)=>a-b));return {groups,balanced:Math.max(...groups.map(g=>g.length))-Math.min(...groups.map(g=>g.length))<=1};}
export function verify(c,r){const flat=r.groups.flat(),where=new Map();r.groups.forEach((g,i)=>g.forEach(v=>where.set(v,i)));if(flat.length!==c.roster.length||new Set(flat).size!==flat.length||flat.some(v=>!c.roster.includes(v))||r.groups.length!==groupCount(c.roster.length)||r.groups.some(g=>!g.length||g.length>MAX_GROUP_SIZE))throw Error('The draw could not be verified. Please try again.');for(const a of c.together)if(new Set(a.map(v=>where.get(v))).size!==1)throw Error('A together request could not be verified.');for(const a of c.apart)if(new Set(a.map(v=>where.get(v))).size!==a.length)throw Error('An apart request could not be verified.');}
